name: "MacOS"
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    paths-ignore:
      - 'docs/*'
      - '*.yml'
      - '*.md'
      - 'LICENSE'

defaults:
  run:
    shell: bash -l {0}

jobs:
  
  build:
    name: "Build & Test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
    steps:
      - name: "Cancel similar actions in progress"
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Install Nim
        run: |
          wget -qO - https://nim-lang.org/choosenim/init.sh | bash -s -- -y
          echo "$HOME/.nimble/bin" >> $GITHUB_PATH

      - name: Verify dependecies
        run: |
          nim --version
          
      - name: Build Library
        run: |
          nim c test.nim