name: Windows
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
    paths-ignore:
      - 'docs/*'
      - '*.yml'
      - '*.md'
      - 'LICENSE'

jobs:
  build:
    name: "Build & Test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
    steps:
      - name: "Cancel similar actions in progress"
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: "Checkout"
        uses: actions/checkout@main
        with:
          submodules: recursive

      - name: "Build Webview"
        run: ./script/build.bat

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: 'git base-devel'

      - name: Install dependencies + Build Library
        shell: msys2 {0}
        run: |
          ls "script\microsoft.web.webview2.1.0.664.37\build\native\x64"
          ls "C:/Program Files (x86)/Windows Kits/10/Include/10.0.20348.0"
          ls "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC"
          pacman --noconfirm -S p7zip
          #pacman --noconfirm -S mingw-w64-x86_64-gcc
          #pacman --noconfirm -S mingw-w64-x86_64-winstorecompat-git
          mkdir dist
          mkdir nim
          #curl -L https://nim-lang.org/download/mingw64.zip -o dist/mingw64.zip
          curl -L https://nim-lang.org/download/dlls.zip -o dist/dlls.zip
          curl -L https://nim-lang.org/download/nim-1.6.4_x64.zip -o dist/nim.zip
          #7z x dist/mingw64.zip -odist
          7z x dist/dlls.zip -obin
          7z x dist/nim.zip -onim
          
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
          export PATH="${{ github.workspace }}/bin":$PATH
          export PATH="${{ github.workspace }}/nim/nim-1.6.4/bin":$PATH
          echo "${{ github.workspace }}/nim/nim-1.6.4/bin" >> $GITHUB_PATH
          ls -la nim/nim-1.6.4
          ls -la nim/nim-1.6.4/bin 
          echo "$GITHUB_PATH"
          
          echo "Running nim"
          nim --version

          nim c --cc:vcc test.nim
